
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
root-package = "github.com/apoc64/qs_go"
go-version = "1.10.3"
install = [ "./..." ]
